# Author: T. Ryan Johnson
# Contact: thomas.johnson@wustl.edu
# Date: March 21, 2020

###
###
###
# Function: a data generating process for a continuous outcome variable Y
# linear in a binary treatment indicator D (no covariates).
#
# NOTE: When num.obs = 50..........
# The starting seed creates an unbalanced sample with 23 control and 27 treated.
# Use seed=02134 for a seed that has balanced treatment and control.

dgen <- function(num.obs=50, intercept=2, treatment.effect=-4, seed=1){
  # Set the seed so that data sets can be generated by simply changing the seed
  # parameter in the function call.
  set.seed(seed)
  
  # Generate a vector of treatment assignment indicators.
  D <- rbinom(num.obs, 1, 0.5) # Any exp. unit has a 50/50 chance of treatment.
  # Generate a vector of mean-zero i.i.d. noise.
  u <- rnorm(50,0,1)
  # Generate the outcome vector.
  Y <- intercept + treatment.effect*D + u
  
  # Generate a data frame to return as output.
  df <- data.frame(cbind(Y,D))
  colnames(df) <- c("Outcome","Treated")
  return(df)
}

