# Author: T. Ryan Johnson
# Contact: thomas.johnson@wustl.edu
# Date: March 21, 2020

###
###
###
# Function: a data generating process for a
#   i) zero intercept, 
#   ii) binary outcome, and
#   iii) no covariate
# data generating process.
# 
# NOTE: When num.obs = 50..........
# The starting seed creates an unbalanced sample with 23 control and 27 treated.
# Use seed=02134 for a seed that has balanced treatment and control.

dgen.simple <- function(num.obs=50, p=0.3, q=0.9, seed=1){
  # Set the seed so that data sets can be generated by simply changing the seed
  # parameter in the function call.
  set.seed(seed)
  
  # Generate the num.obs x 1 vector of treatment assignment indicators.
  D <- rbinom(num.obs, 1, 0.5) # Any exp. unit has a 50/50 chance of treatment.
  
  # Generate outcomes associated with the treatment assignment indicators D.
  Y <- rep(NA, num.obs)
  for(i in 1:num.obs){
    if(D[i]==0){ # If the exp. unit was part of the control group, ...
      Y[i] <- rbinom(1,1,p) # then there is a p percent chance that Y_i = 1.
    } else { # If the exp. unit was part of the treatment group, ...
      Y[i] <- rbinom(1,1,q) # then there is a q percent chance that Y_i = 1.
    }
  }
  
  # Generate a data frame to return as output.
  df <- data.frame(cbind(Y,D))
  colnames(df) <- c("Outcome","Treated")
  return(df)
}